version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/brizy-ssl-helper
permissions:
  - object: /var/www/brizy-ssl-helper
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: getssl.sh
      runas: root